from feapder import Item

import tools


class NewsItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i news 1
    """

    __table_name__ = "news"
    __unique_key__ = ["id"]
    def __init__(self, *args, **kwargs):

        self.title = kwargs.get('title')
        self.content = kwargs.get('content')
        self.publish_date = kwargs.get('publish_date')
        self.platform = kwargs.get('platform')
        self.tags = kwargs.get('tags')
        self.id = tools.get_md5(self.title, self.platform)



