# -*- coding: utf-8 -*-
"""
Created on 2024-09-20 16:16:54
---------
@summary:
---------
@author: ysl
"""

from feapder import Item


class ReplyItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i reply 1
    """

    __table_name__ = "reply"

    def __init__(self, *args, **kwargs):
        self.sub_id = kwargs.get('sub_id')
        self.reply_id = kwargs.get('reply_id')
        self.content = kwargs.get('content')
        self.reply_time = kwargs.get('reply_time')
